<?php 

$formatHelper = $this->helper('Mgt\DeveloperToolbar\Helper\Format');

$mode = $this->getMode();
$magentoVersion = $this->getMagentoVersion();
$cacheStorage = $this->getCacheStorage();
$areaCode = $this->getAreaCode();
$sessionSaveHandler = $this->getSessionSaveHandler();
$phpVersion = $this->getPhpVersion();
$phpMemoryLimit = $this->getPhpMemoryLimit();
$phpMaxExecutionTime = $this->getPhpMaxExecutionTime();
$mysqlVersion = $this->getMysqlVersion();
$modules = $this->getModules();

?>

<div class="container">
  <div class="mgt-developer-toolbar-sidebar-dashboard">

    <h2><?php echo __('General Information'); ?></h2>

    <div class="mgt-developer-toolbar-sidebar-metrics">
    
      <div class="mgt-developer-toolbar-sidebar-metric">
        <span class="value"><?php echo $magentoVersion; ?></span>
        <span class="label"><?php echo __('Magento Version'); ?></span>
      </div>

      <div class="mgt-developer-toolbar-sidebar-metric">
        <span class="value"><?php echo $areaCode; ?></span>
        <span class="label"><?php echo __('Area'); ?></span>
      </div>
      
      <div class="mgt-developer-toolbar-sidebar-metric">
        <span class="value"><?php echo $cacheStorage; ?></span>
        <span class="label"><?php echo __('Cache Storage'); ?></span>
      </div>
    
      <div class="mgt-developer-toolbar-sidebar-metric">
        <span class="value"><?php echo $sessionSaveHandler; ?></span>
        <span class="label"><?php echo __('Session Storage'); ?></span>
      </div>

    </div>
  
    <h2><?php echo __('Server Configuration'); ?></h2>

    <div class="mgt-developer-toolbar-sidebar-metrics">
    
      <div class="mgt-developer-toolbar-sidebar-metric">
        <span class="value"><?php echo $phpVersion; ?></span>
        <span class="label"><?php echo __('PHP Version'); ?></span>
      </div>
    
      <div class="mgt-developer-toolbar-sidebar-metric">
        <span class="value"><?php echo $formatHelper->formatBytes($phpMemoryLimit); ?></span>
        <span class="label"><?php echo __('PHP Memory Limit'); ?></span>
      </div>
    
      <div class="mgt-developer-toolbar-sidebar-metric">
        <span class="value"><?php echo $phpMaxExecutionTime; ?> s</span>
        <span class="label"><?php echo __('PHP Max Execution Time'); ?></span>
      </div>
    
      <div class="mgt-developer-toolbar-sidebar-metric">
        <span class="value"><?php echo $mysqlVersion; ?></span>
        <span class="label"><?php echo __('MySQL Version'); ?></span>
      </div>

      <!--  
      <div class="mgt-developer-toolbar-sidebar-metric">
        <span class="value">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="28" height="28" viewBox="0 0 12 12" enable-background="new 0 0 12 12" xml:space="preserve">
            <path fill="#5E976E" d="M12,3.1c0,0.4-0.1,0.8-0.4,1.1L5.9,9.8c-0.3,0.3-0.6,0.4-1,0.4c-0.4,0-0.7-0.1-1-0.4L0.4,6.3
              C0.1,6,0,5.6,0,5.2c0-0.4,0.2-0.7,0.4-0.9C0.6,4,1,3.9,1.3,3.9c0.4,0,0.8,0.1,1.1,0.4l2.5,2.5l4.7-4.7c0.3-0.3,0.7-0.4,1-0.4
              c0.4,0,0.7,0.2,0.9,0.4C11.8,2.4,12,2.7,12,3.1z">
            </path>
          </svg>
        </span>
        <span class="label">OPcache</span>
      </div>
      -->    
    
    </div>
  
     <h2><?php echo __('Modules'); ?></h2>
   
     <table class="data-table" cellpadding="0" cellspacing="0">
       <thead>
         <tr>
           <th width="90%"><?php echo __('Name'); ?></th>
           <th><?php echo __('Enabled'); ?></th>
         </tr>
       </thead>
       <tbody>
         <?php foreach($modules as $moduleName => $enabled): ?>
           <tr>
             <td>
               <?php echo $moduleName; ?>
             </td>
             <td>
               <?php if (true === $enabled): ?>
                 <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="28" height="28" viewBox="0 0 12 12" enable-background="new 0 0 12 12" xml:space="preserve">
                   <path fill="#5E976E" d="M12,3.1c0,0.4-0.1,0.8-0.4,1.1L5.9,9.8c-0.3,0.3-0.6,0.4-1,0.4c-0.4,0-0.7-0.1-1-0.4L0.4,6.3
                     C0.1,6,0,5.6,0,5.2c0-0.4,0.2-0.7,0.4-0.9C0.6,4,1,3.9,1.3,3.9c0.4,0,0.8,0.1,1.1,0.4l2.5,2.5l4.7-4.7c0.3-0.3,0.7-0.4,1-0.4c0.4,0,0.7,0.2,0.9,0.4C11.8,2.4,12,2.7,12,3.1z">
                   </path>
                 </svg>
              <?php else: ?>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="28" height="28" viewBox="0 0 12 12" enable-background="new 0 0 12 12" xml:space="preserve">
                  <path fill="#B0413E" d="M10.4,8.4L8,6l2.4-2.4c0.8-0.8,0.7-1.6,0.2-2.2C10,0.9,9.2,0.8,8.4,1.6L6,4L3.6,1.6C2.8,0.8,2,0.9,1.4,1.4
                    C0.9,2,0.8,2.8,1.6,3.6L4,6L1.6,8.4C0.8,9.2,0.9,10,1.4,10.6c0.6,0.6,1.4,0.6,2.2-0.2L6,8l2.4,2.4c0.8,0.8,1.6,0.7,2.2,0.2C11.1,10,11.2,9.2,10.4,8.4z">
                  </path>
                </svg>
              <?php endif ?>
             </td>
           </tr>
         <?php endforeach ?>
       </tbody>
     </table>
  </div>
</div>