<div class="mgt-developer-toolbar" id="mgt-developer-toolbar-container">
  <img class="magento-logo" src="<?php echo Mage::helper('mgt_developertoolbar')->getMediaUrl().'mgt_developertoolbar/logo.png'; ?>" alt="" />
    <?php if ($this->getItems()): ?>
    <ul id="mgt-developer-toolbar">
        <?php foreach ($this->getItems() as $item): ?>
          <?php echo $item->render(); ?>
        <?php endforeach ?>
    </ul>
    <?php endif ?>
</div>

<?php foreach ($this->getItems() as $item): ?>
  <?php if ($item->getContent()): ?>
    <div class="mgt-developer-toolbar-details" id="mgt-developer-toolbar-item-<?php echo $item->getName(); ?>-details" style="display:none;">
      <?php echo $item->renderContent(); ?>
    </div>
  <?php endif ?>
<?php endforeach ?>
