<?php
// @codingStandardsIgnoreFile
/** @var $block Mgt\DeveloperToolbar\Block\Toolbar\Block\Info */

$urlBuilder = $block->getUrlBuilder();
$controllerModule = $block->getControllerModule();
$controllerClassName = $block->getControllerClassName();
$controllerActionName = $block->getControllerActionName();
$mode = ucfirst($block->getMode());
$token = $block->getToken();

?>

<div class="mgt-developer-toolbar-block mgt-developer-toolbar-block-info">
  <a href="<?php echo $urlBuilder->getUrl('mgtdevelopertoolbar/toolbar/container/execute', ['block' => 'dashboard', 'token' => $token]); ?>">
    <span class="mode"><?php echo $mode; ?></span>
  </a>
  <div class="mgt-developer-toolbar-block-information" style="display:none;">
    <ul>
      <li>
         <strong><?php echo __('Mode') ?>:</strong> <?php echo $mode; ?>
      </li>
      <li>
         <strong><?php echo __('Controler Module') ?>:</strong> <?php echo $controllerModule; ?>
      </li>
      <li>
         <strong><?php echo __('Controler Class') ?>:</strong> <?php echo $controllerClassName; ?>
      </li>
      <li>
         <strong><?php echo __('Controler Action Name') ?>:</strong> <?php echo $controllerActionName; ?>
      </li>
    </ul>
  </div>
</div>